CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 6
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - mapillary_cityscapes_sem_seg_val
  TRAIN:
  - mapillary_cityscapes_sem_seg_train
  - cityscapes_fine_sem_seg_train
  UNSEEN_LABEL_SET: datasets/unknown/unknown_K20.txt
GLOBAL:
  HACK: 1.0
INPUT:
  COCO_PROXY_SIZE: 50000
  COCO_ROOT: coco/
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: true
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE:
    - 512
    - 1024
    TYPE: absolute
  DATASET_MAPPER_NAME: mask_former_semantic_coco_mix
  FORMAT: RGB
  IMAGE_SIZE: 1024
  MASK_FORMAT: polygon
  MAX_SCALE: 2.0
  MAX_SIZE_TEST: 2048
  MAX_SIZE_TRAIN: 8192
  MIN_SCALE: 0.1
  MIN_SIZE_TEST: 2048
  MIN_SIZE_TRAIN:
  - 1024
  - 1228
  MIN_SIZE_TRAIN_SAMPLING: choice
  OOD_LABEL: 254
  OOD_PROB: 0.5
  RANDOM_FLIP: horizontal
  REPEAT_INSTANCE_MASKS: 1
  SIZE_DIVISIBILITY: -1
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
      - 64
      - 128
      - 256
      - 512
  BACKBONE:
    FREEZE_AT: 0
    NAME: D2SwinTransformer
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: []
    NORM: ''
    OUT_CHANNELS: 256
  FREEZE_BACKBONE: true
  FREEZE_PIXEL_DECODER: true
  FREEZE_TRANSFORMER_DECODER: false
  FREEZE_TRANSFORMER_DECODER_EXCEPT_MLP: true
  FREEZE_TRANSFORMER_DECODER_EXCEPT_MLP_AND_OOD_PRED: false
  FREEZE_TRANSFORMER_DECODER_EXCEPT_OBJECT_QUERIES: false
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_FORMER:
    CLASS_WEIGHT: 2.0
    DEC_LAYERS: 2
    DEEP_SUPERVISION: true
    DENSE_HYBRID_BETA: 0.03
    DENSE_HYBRID_LOSS: false
    DENSE_HYBRID_WEIGHT: 1.0
    DICE_WEIGHT: 5.0
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.0
    ENC_LAYERS: 0
    ENFORCE_INPUT_PROJ: false
    GAMBLER_LOSS: false
    GAMBLER_WEIGHT: 1.0
    HIDDEN_DIM: 256
    IMPORTANCE_SAMPLE_RATIO: 0.75
    INLIER_UPPER_THRESHOLD: -0.0
    MASK_WEIGHT: 5.0
    MATCHER: HungarianMatcher
    NHEADS: 8
    NO_OBJECT_WEIGHT: 0.1
    NUM_OBJECT_QUERIES: 100
    OPEN_PANOPTIC: true
    OUTLIER_LOSS_FUNC: squared_hinge
    OUTLIER_LOSS_TARGET: nls
    OUTLIER_LOWER_THRESHOLD: 5.0
    OUTLIER_SUPERVISION: true
    OUTLIER_WEIGHT: 1.0
    OVERSAMPLE_RATIO: 3.0
    PEBAL_OOD_REG: 0.1
    PEBAL_REWARD: 4.5
    PRE_NORM: false
    SCORE_NORM: tanh
    SEM_SEG_UNLABELED_REGION: true
    SIZE_DIVISIBILITY: 32
    SMOOTHNESS_LOSS: false
    SMOOTHNESS_SCORE: nls
    SMOOTHNESS_WEIGHT: 3.0e-06
    SPARSITY_LOSS: false
    SPARSITY_WEIGHT: 0.0005
    TEST:
      INSTANCE_ON: false
      OBJECT_MASK_THRESHOLD: 0.0
      OVERLAP_THRESHOLD: 0.8
      PANOPTIC_ON: false
      SEMANTIC_ON: true
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false
    TRAIN_NUM_POINTS: 12544
    TRANSFORMER_DECODER_NAME: MultiScaleMaskedTransformerDecoder
    TRANSFORMER_IN_FEATURE: multi_scale_pixel_decoder
    UNLABELED_REGION: true
    USE_POINT_REND: false
  MASK_ON: false
  META_ARCHITECTURE: MaskFormer
  MVIT:
    ACT_LAYER: GELU
    ADAPTIVE_KV_STRIDE: 4
    ADAPTIVE_WINDOW_SIZE: 56
    DEPTH: 24
    DROP_PATH_RATE: 0.4
    EMBED_DIM: 96
    IMG_SIZE: 224
    IN_CHANS: 3
    LAST_BLOCK_INDEXES:
    - 1
    - 4
    - 20
    - 23
    MLP_RATIO: 4.0
    NORM_LAYER: LayerNorm
    NUM_HEADS: 1
    OUT_FEATURES:
    - scale2
    - scale3
    - scale4
    - scale5
    PATCH_KERNEL:
    - 7
    - 7
    PATCH_PADDING:
    - 3
    - 3
    PATCH_STRIDE:
    - 4
    - 4
    PRETRAIN_IMG_SIZE: 224
    PRETRAIN_USE_CLS_TOKEN: true
    QKV_BIAS: true
    QKV_POOL_KERNEL:
    - 3
    - 3
    REL_POS_ZERO_INIT: true
    RESIDUAL_POOLING: true
    USE_ABS_POS: false
    USE_ACT_CHECKPOINT: false
    USE_REL_POS: true
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.12
  - 57.375
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES4_DILATION: 1
    RES5_DILATION: 1
    RES5_MULTI_GRID:
    - 1
    - 1
    - 1
    STEM_OUT_CHANNELS: 64
    STEM_TYPE: basic
    STRIDE_IN_1X1: false
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NORM: ''
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    CLS_AGNOSTIC_BBOX_REG: false
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: ''
    NORM: ''
    NUM_CONV: 0
    NUM_FC: 0
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES:
    - res4
    IOU_LABELS:
    - 0
    - 1
    IOU_THRESHOLDS:
    - 0.5
    NAME: Res5ROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 80
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: true
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: false
    CONV_DIM: 256
    NAME: MaskRCNNConvUpsampleHead
    NORM: ''
    NUM_CONV: 0
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    BOUNDARY_THRESH: -1
    CONV_DIMS:
    - -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - res4
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 12000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    ASPP_CHANNELS: 256
    ASPP_DILATIONS:
    - 6
    - 12
    - 18
    ASPP_DROPOUT: 0.1
    COMMON_STRIDE: 4
    CONVS_DIM: 256
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES:
    - res5
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    IGNORE_VALUE: 255
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    LOSS_TYPE: hard_pixel_mining
    LOSS_WEIGHT: 1.0
    MASK_DIM: 256
    NAME: MaskFormerHead
    NORM: GN
    NUM_CLASSES: 19
    PIXEL_DECODER_NAME: MSDeformAttnPixelDecoder
    PROJECT_CHANNELS:
    - 48
    PROJECT_FEATURES:
    - res2
    TRANSFORMER_ENC_LAYERS: 6
    USE_DEPTHWISE_SEPARABLE_CONV: false
  SWIN:
    APE: false
    ATTN_DROP_RATE: 0.0
    DEPTHS:
    - 2
    - 2
    - 18
    - 2
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 192
    MLP_RATIO: 4.0
    NUM_HEADS:
    - 6
    - 12
    - 24
    - 48
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    PATCH_NORM: true
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 384
    QKV_BIAS: true
    QK_SCALE: null
    USE_CHECKPOINT: false
    WINDOW_SIZE: 12
  VIT:
    ACT_LAYER: GELU
    DEPTH: 12
    DROP_PATH_RATE: 0.1
    EMBED_DIM: 768
    IMG_SIZE: 1024
    IN_CHANS: 3
    MLP_RATIO: 4.0
    NORM_LAYER: LayerNorm
    NUM_HEADS: 12
    OUT_FEATURE: last_feat
    PATCH_SIZE: 16
    PRETRAIN_IMG_SIZE: 224
    PRETRAIN_USE_CLS_TOKEN: true
    QKV_BIAS: true
    REL_POS_ZERO_INIT: true
    RESIDUAL_BLOCK_INDEXES: []
    USE_ABS_POS: true
    USE_ACT_CHECKPOINT: false
    USE_REL_POS: true
    WINDOW_BLOCK_INDEXES:
    - - 0
      - 1
      - 3
      - 4
      - 6
      - 7
      - 9
      - 10
    WINDOW_SIZE: 14
  WEIGHTS: ckpts/swin_l_1dl/model_final.pth
  WIDE_RESNET:
    DILATION: true
    DIST_BN: false
    STRUCTURE:
    - 3
    - 3
    - 6
    - 3
    - 1
    - 1
OUTPUT_DIR: ./ckpts/swin_l_1dl_rba_ood_map_coco/
SEED: 41035104
SOLVER:
  AMP:
    ENABLED: true
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 1.0e-05
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 0.01
    ENABLED: true
    NORM_TYPE: 2.0
  FORCE_REGION_PARTITION: false
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  LR_SCHEDULER_NAME: WarmupPolyLR
  MAX_ITER: 90000
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: ADAMW
  POLY_LR_CONSTANT_ENDING: 0.0
  POLY_LR_POWER: 0.9
  REFERENCE_WORLD_SIZE: 0
  STEPS:
  - 30000
  USE_WANDB: false
  WANDB_NAME: ''
  WANDB_PROJECT: mask2former
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES:
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 2000000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
