_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2ViT"
  VIT:
    OUT_FEATURE: "last_feat"
  SEM_SEG_HEAD:
    IN_FEATURES: ["last_feat"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["last_feat"]
  MASK_FORMER:
    DEC_LAYERS: 2
  WEIGHTS: "detectron2://ImageNetPretrained/MAE/mae_pretrain_vit_base.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
