_BASE_: maskformer2_R50_bs16_90k.yaml
MODEL:
  WEIGHTS: "model_logs/mask2former_resnet101_1_dec_layer_res5/model_final.pth"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "BN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  MASK_FORMER:
    DEC_LAYERS: 2
    OUTLIER_SUPERVISION: True
    OUTLIER_LOSS_TARGET: "nls"
  SEM_SEG_HEAD:
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res5"]
  FREEZE_PIXEL_DECODER: True 
  FREEZE_BACKBONE: True
INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic_coco_mix"
SOLVER:
  MAX_ITER: 5000