_BASE_: ../maskformer2_R50_bs16_300k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  MASK_FORMER:
    DEC_LAYERS: 2
  SEM_SEG_HEAD:
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 19
  WEIGHTS: "./ckpts/swin_b_1dl/model_final.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
DATASETS:
  TRAIN: ("mapillary_cityscapes_sem_seg_train",)
  TEST: ("mapillary_cityscapes_sem_seg_val",)
SOLVER:
  MAX_ITER: 30000
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 2048) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TRAIN: 8192
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  SIZE_DIVISIBILITY: -1